run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - internal/experimental  # Exclude experimental code from linting

linters:
  enable:
    # Default linters
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    
    # Additional linters for code quality
    - gocyclo        # Check function complexity
    - gosec         # Security checks
    - misspell      # Check spelling
    - prealloc      # Memory allocation optimisation
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused parameters
    - whitespace    # Check whitespace style
    - wsl           # Whitespace style linter
    - revive        # Drop-in replacement for golint
    - gocritic      # Checks for bugs, performance and style issues
    - godot         # Check comment endings
    - goimports     # Manage imports
    - bodyclose     # Check for unclosed HTTP response bodies
    - noctx         # Check for context propagation
    - exportloopref # Check for loop variable reference export
    - gomodguard    # Check for disallowed modules

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gomodguard:
    blocked:
      modules:
        - github.com/pkg/errors:
            recommendations:
              - golang.org/x/xerrors
            reason: "deprecated: use the standard library errors package instead"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - gosec
      text: "G104"  # Duplicate of errcheck
