repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/golangci/golangci-lint
  rev: v1.55.2
  hooks:
    - id: golangci-lint
      args: [--timeout=5m]

- repo: https://github.com/securego/gosec
  rev: 2.18.2
  hooks:
    - id: gosec
      args: [-exclude=G104]  # Exclude error checking on os.CreateTemp in tests

- repo: local
  hooks:
    - id: go-fmt
      name: go fmt
      entry: gofmt -l -w
      language: system
      types: [go]
      pass_filenames: true
