# Instance identification
[instance]
name = "snmp.collector.hedgehog.internal"
log_level = "debug"

# Elasticsearch connection settings
[elasticsearch]
hosts = ["http://elasticsearch.hedgehog.internal:9200"]
index = "service_configuration"
certificate_hash = ""

[elasticsearch.auth]
username = "hedgehog_admin"
password = "changeme"

# Concurrency settings
[concurrency]
max_scrapers = 10
max_writers = 5

# Timing settings
[timing]
config_reload_interval = "5m"
scrape_timeout = "30s"
write_timeout = "10s"

# Backoff settings
[backoff]
initial_interval = "1s"
max_interval = "1m"
max_retries = 3
multiplier = 2.0

# Metrics settings
[metrics]
port = 9090
path = "/metrics"
