name: snmp-prometheus-getter

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch.hedgehog.internal
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      hedgehog.internal:
        aliases:
          - elasticsearch.hedgehog.internal

  snmp-exporter:
    image: prom/snmp-exporter:v0.25.0
    container_name: snmp-exporter.hedgehog.internal
    ports:
      - "9116:9116"
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9116/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      hedgehog.internal:
        aliases:
          - snmp-exporter.hedgehog.internal

  snmp-simulator:
    image: ghcr.io/lextudio/docker-snmpsim:master
    container_name: snmp-simulator.hedgehog.internal
    ports:
      - "11161:11161/udp"
    environment:
      - SNMPSIM_LISTEN_IP=0.0.0.0
      - SNMPSIM_LISTEN_PORT=11161
      - SNMPSIM_COMMUNITY=public
      - SNMPSIM_PROTOCOL=v2c
    volumes:
      - ./snmp_data:/usr/local/snmpsim/data
    networks:
      hedgehog.internal:
        aliases:
          - snmp-simulator.hedgehog.internal
    restart: unless-stopped

  snmp-getter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snmp-getter.hedgehog.internal
    volumes:
      - ./config.toml:/app/config.toml:ro
    networks:
      hedgehog.internal:
        aliases:
          - snmp-getter.hedgehog.internal
    depends_on:
      - elasticsearch
      - snmp-exporter
      - snmp-simulator
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  setup-elasticsearch:
    image: curlimages/curl:latest
    volumes:
      - ./scripts/setup_test_config.sh:/setup_test_config.sh:ro
      - ./elasticsearch_config.example.json:/config/elasticsearch_device1_config.json:ro
    entrypoint: ["/bin/sh", "/setup_test_config.sh"]
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      hedgehog.internal:
        aliases:
          - setup-elasticsearch.hedgehog.internal

  troubleshoot:
    image: ubuntu:latest
    container_name: troubleshoot.hedgehog.internal
    command: tail -f /dev/null
    networks:
      hedgehog.internal:
        aliases:
          - troubleshoot.hedgehog.internal
    volumes:
      - /etc/hosts:/etc/hosts:ro
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "22"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  elasticsearch_data:

networks:
  hedgehog.internal:
    external: true
