[project]
name = "go-snmp-prometheus-getter-dev"
version = "0.1.0"
description = "Development environment for go-snmp-prometheus-getter"
requires-python = "==3.13.2"
dependencies = [
    "pre-commit>=4.1.0",
]
